const LABELS: Record<string, string> = {
  current_daily_budget: "Текущий дневной бюджет",
  proposed_daily_budget: "Новый дневной бюджет",
  currency: "Валюта",
  current_status: "Текущий статус",
  proposed_status: "Новый статус",
  current_targeting_hash: "Текущие настройки аудитории",
  proposed_targeting: "Предложенная аудитория",
  allocation_percent: "Доля участников, %",
  duration_days: "Продолжительность, дней",
  audience_segment: "Сегмент аудитории",
  experiment_key: "Эксперимент",
  ACTIVE: "Активно",
  PAUSED: "Приостановлено",
  DELETED: "Удалено",
  ARCHIVED: "В архиве",
  region: "Регион",
  placement: "Площадка",
  age: "Возраст",
  gender: "Пол",
  hour: "Час",
  day: "День",
  "growth-agent": "Рост и конверсия",
  "marketing-agent": "Рост и конверсия",
  "retention-agent": "Удержание и лояльность",
  "operations-orchestrator": "Главный оркестратор",
  "technical-agent": "Надёжность приложения",
  "growth.advertising": "Реклама",
  "growth.funnel.analyze": "Воронка продаж",
  "retention.engagement.analyze": "Вовлечённость пользователей",
  "retention.parents.analyze": "Родители MANA — тарифы и подключения",
  mana_parent_summary: "Сводка родителей MANA",
  manakids_parent_api: "Parent API · только MANA",
  registered: "Зарегистрирован",
  enabled: "Включён",
  disabled: "Выключен",
  paused: "Приостановлен",
  healthy: "Доступен",
  degraded: "Есть ограничения",
  unhealthy: "Ошибка подключения",
  unconfigured: "Не подключён",
  unknown: "Нет свежей проверки",
  unavailable: "Нет данных",
  queued: "В очереди",
  collecting: "Собирает данные",
  normalizing: "Подготавливает данные",
  analyzing: "Анализирует",
  proposing: "Готовит предложения",
  policy_check: "Проверяет ограничения",
  waiting_approval: "Ожидает согласования",
  awaiting_approval: "Ожидает согласования",
  executing: "Выполняется",
  verifying: "Проверяет результат",
  reporting: "Готовит отчёт",
  completed: "Завершён",
  failed: "Ошибка",
  cancelled: "Отменён",
  pending: "Ожидает решения",
  approved: "Одобрено",
  rejected: "Отклонено",
  expired: "Срок истёк",
  succeeded: "Выполнено",
  dry_run: "Проверка без изменений",
  outcome_uncertain: "Результат требует проверки",
  read: "Только чтение",
  propose: "Подготовка предложений",
  write: "Изменение данных",
  financial: "Финансовое действие",
  info: "Информация",
  warning: "Требует внимания",
  critical: "Критично",
  stopped: "Остановлено",
  armed: "Разрешено политикой",
  analysis: "Анализ",
  nightly_report: "Ежедневный отчёт",
  enable: "Включить",
  disable: "Выключить",
  retention_engagement_analysis: "Отчёт о вовлечённости",
  funnel_analysis: "Отчёт по воронке",
  collect: "Сбор данных",
  normalize: "Подготовка данных",
  analyze: "Анализ",
  approval: "Согласование",
  execute: "Выполнение",
  verify: "Проверка результата",
  report: "Отчёт",
  viewer: "Наблюдатель",
  operator: "Оператор",
  approver: "Согласующий",
  admin: "Администратор",
  increase_budget: "Увеличить бюджет",
  decrease_budget: "Уменьшить бюджет",
  pause: "Приостановить",
  resume: "Возобновить",
  scale_audience: "Расширить аудиторию",
  disable_audience: "Отключить аудиторию",
  maintain: "Оставить без изменений",
  create_experiment: "Создать эксперимент",
  stop_experiment: "Остановить эксперимент",
  manakids_admin_api: "Приложение Manakids",
  firebase_operational_telemetry: "Firebase: состояние устройств",
  firebase_app_activity: "Firebase: события приложения",
  google_analytics_4: "Google Analytics: активность приложения",
  mobile_product_analytics_unconfigured: "Мобильная аналитика — не подключена",
  fake_manakids_admin_api: "Тестовые данные Manakids",
  fake_firestore_activity: "Тестовые события приложения",
  fake_firebase_operational_telemetry: "Тестовые данные устройств",
  meta: "Meta: рекламный кабинет",
  fake_meta: "Тестовый рекламный кабинет",
  product_analytics: "Продуктовая аналитика",
  billing: "Оплаты и подписки",
  attribution: "Источники привлечения",
  fake_experiments: "Тестовые эксперименты",
  live_read_only: "Реальные данные, только чтение",
  fake_executable: "Тестовая среда",
};

export function labelFor(value: string | null | undefined): string {
  if (!value) return "Нет данных";
  return LABELS[value] ?? value.replaceAll("_", " ");
}

const DESCRIPTIONS: Record<string, string> = {
  "growth-agent":
    "Анализ рекламы и воронки. Готовит предложения по привлечению и конверсии; реальные изменения рекламы отключены.",
  "retention-agent":
    "Анализ сохранённых данных об активности и полноте источников. Персональные предложения и изменение подписок пока не подключены.",
  "growth.advertising":
    "Показатели рекламы, сравнение аудиторий и креативов, рекомендации.",
  "growth.funnel.analyze":
    "Поиск потерь в воронке и тестовые эксперименты. Пока на демонстрационных данных.",
  "retention.engagement.analyze":
    "Активность пользователей и качество данных. Без отправки сообщений и изменения подписок.",
  "retention.parents.analyze":
    "Ручная ограниченная выборка родителей только MANA. Текущий тариф может быть бесплатным; это не история платежей и не оценка оттока.",
};

export function descriptionFor(value: string): string {
  return (
    DESCRIPTIONS[value] ?? "Подробности доступны в технической информации."
  );
}
