"""create operation agent platform

Revision ID: a57f606d9211
Revises:
Create Date: 2026-07-22 14:08:54.422890
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a57f606d9211"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_agents",
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index(
        op.f("ix_operation_agents_status"), "operation_agents", ["status"], unique=False
    )
    op.create_table(
        "operation_audit_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_operation_audit_events_actor_id"),
        "operation_audit_events",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_audit_events_agent_id"),
        "operation_audit_events",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_audit_events_correlation_id"),
        "operation_audit_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_audit_events_event_type"),
        "operation_audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_audit_events_occurred_at"),
        "operation_audit_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_audit_events_run_id"), "operation_audit_events", ["run_id"], unique=False
    )
    op.create_table(
        "operation_integration_health",
        sa.Column("integration_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("integration_id"),
    )
    op.create_index(
        op.f("ix_operation_integration_health_checked_at"),
        "operation_integration_health",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_integration_health_status"),
        "operation_integration_health",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_job_locks",
        sa.Column("lock_key", sa.String(length=180), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("lock_key"),
    )
    op.create_index(
        op.f("ix_operation_job_locks_expires_at"),
        "operation_job_locks",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "operation_system_controls",
        sa.Column("control_key", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("control_key"),
    )
    op.create_table(
        "operation_agent_configurations",
        sa.Column("configuration_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["operation_agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("configuration_id"),
        sa.UniqueConstraint("agent_id", "version"),
    )
    op.create_index(
        op.f("ix_operation_agent_configurations_active"),
        "operation_agent_configurations",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_configurations_agent_id"),
        "operation_agent_configurations",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "operation_agent_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["operation_agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("agent_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_operation_agent_runs_agent_id"), "operation_agent_runs", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_operation_agent_runs_correlation_id"),
        "operation_agent_runs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_runs_started_at"),
        "operation_agent_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_runs_status"), "operation_agent_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_operation_agent_runs_trigger"), "operation_agent_runs", ["trigger"], unique=False
    )
    op.create_table(
        "operation_agent_schedules",
        sa.Column("schedule_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["operation_agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id"),
    )
    op.create_index(
        op.f("ix_operation_agent_schedules_agent_id"),
        "operation_agent_schedules",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_schedules_enabled"),
        "operation_agent_schedules",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_schedules_job_type"),
        "operation_agent_schedules",
        ["job_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_schedules_next_run_at"),
        "operation_agent_schedules",
        ["next_run_at"],
        unique=False,
    )
    op.create_table(
        "operation_action_proposals",
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_object_id", sa.String(length=255), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "idx_operation_proposal_object",
        "operation_action_proposals",
        ["provider", "provider_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_action_type"),
        "operation_action_proposals",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_agent_id"),
        "operation_action_proposals",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_created_at"),
        "operation_action_proposals",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_expires_at"),
        "operation_action_proposals",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_run_id"),
        "operation_action_proposals",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_proposals_status"),
        "operation_action_proposals",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_agent_reports",
        sa.Column("report_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("report_type", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("human_readable", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_index(
        op.f("ix_operation_agent_reports_agent_id"),
        "operation_agent_reports",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_reports_created_at"),
        "operation_agent_reports",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_reports_report_type"),
        "operation_agent_reports",
        ["report_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_agent_reports_run_id"),
        "operation_agent_reports",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "operation_data_snapshots",
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_index(
        op.f("ix_operation_data_snapshots_agent_id"),
        "operation_data_snapshots",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_data_snapshots_checksum"),
        "operation_data_snapshots",
        ["checksum"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_data_snapshots_collected_at"),
        "operation_data_snapshots",
        ["collected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_data_snapshots_run_id"),
        "operation_data_snapshots",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "operation_recommendations",
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("provider_object_id", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_operation_recommendations_action_type"),
        "operation_recommendations",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_recommendations_created_at"),
        "operation_recommendations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_recommendations_expires_at"),
        "operation_recommendations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_recommendations_provider_object_id"),
        "operation_recommendations",
        ["provider_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_recommendations_run_id"),
        "operation_recommendations",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "operation_action_executions",
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["operation_action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_operation_action_executions_attempted_at"),
        "operation_action_executions",
        ["attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_executions_proposal_id"),
        "operation_action_executions",
        ["proposal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_executions_run_id"),
        "operation_action_executions",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_executions_status"),
        "operation_action_executions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_analyses",
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["operation_data_snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("analysis_id"),
    )
    op.create_index(
        op.f("ix_operation_analyses_calculated_at"),
        "operation_analyses",
        ["calculated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_analyses_run_id"), "operation_analyses", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_operation_analyses_snapshot_id"),
        "operation_analyses",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "operation_approval_requests",
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["operation_action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        op.f("ix_operation_approval_requests_expires_at"),
        "operation_approval_requests",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_approval_requests_proposal_id"),
        "operation_approval_requests",
        ["proposal_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_operation_approval_requests_requested_at"),
        "operation_approval_requests",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_approval_requests_status"),
        "operation_approval_requests",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_action_verifications",
        sa.Column("verification_id", sa.String(length=64), nullable=False),
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["operation_action_executions.execution_id"],
        ),
        sa.PrimaryKeyConstraint("verification_id"),
    )
    op.create_index(
        op.f("ix_operation_action_verifications_checked_at"),
        "operation_action_verifications",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_action_verifications_execution_id"),
        "operation_action_verifications",
        ["execution_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_operation_action_verifications_status"),
        "operation_action_verifications",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_approval_decisions",
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("decided_by", sa.String(length=128), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["operation_approval_requests.approval_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        op.f("ix_operation_approval_decisions_decided_at"),
        "operation_approval_decisions",
        ["decided_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_approval_decisions_proposal_id"),
        "operation_approval_decisions",
        ["proposal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_approval_decisions_status"),
        "operation_approval_decisions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "operation_findings",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("finding_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["operation_analyses.analysis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operation_agent_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(
        op.f("ix_operation_findings_created_at"), "operation_findings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_operation_findings_finding_type"),
        "operation_findings",
        ["finding_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_findings_run_id"), "operation_findings", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_operation_findings_severity"), "operation_findings", ["severity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_findings_severity"), table_name="operation_findings")
    op.drop_index(op.f("ix_operation_findings_run_id"), table_name="operation_findings")
    op.drop_index(op.f("ix_operation_findings_finding_type"), table_name="operation_findings")
    op.drop_index(op.f("ix_operation_findings_created_at"), table_name="operation_findings")
    op.drop_table("operation_findings")
    op.drop_index(
        op.f("ix_operation_approval_decisions_status"), table_name="operation_approval_decisions"
    )
    op.drop_index(
        op.f("ix_operation_approval_decisions_proposal_id"),
        table_name="operation_approval_decisions",
    )
    op.drop_index(
        op.f("ix_operation_approval_decisions_decided_at"),
        table_name="operation_approval_decisions",
    )
    op.drop_table("operation_approval_decisions")
    op.drop_index(
        op.f("ix_operation_action_verifications_status"),
        table_name="operation_action_verifications",
    )
    op.drop_index(
        op.f("ix_operation_action_verifications_execution_id"),
        table_name="operation_action_verifications",
    )
    op.drop_index(
        op.f("ix_operation_action_verifications_checked_at"),
        table_name="operation_action_verifications",
    )
    op.drop_table("operation_action_verifications")
    op.drop_index(
        op.f("ix_operation_approval_requests_status"), table_name="operation_approval_requests"
    )
    op.drop_index(
        op.f("ix_operation_approval_requests_requested_at"),
        table_name="operation_approval_requests",
    )
    op.drop_index(
        op.f("ix_operation_approval_requests_proposal_id"), table_name="operation_approval_requests"
    )
    op.drop_index(
        op.f("ix_operation_approval_requests_expires_at"), table_name="operation_approval_requests"
    )
    op.drop_table("operation_approval_requests")
    op.drop_index(op.f("ix_operation_analyses_snapshot_id"), table_name="operation_analyses")
    op.drop_index(op.f("ix_operation_analyses_run_id"), table_name="operation_analyses")
    op.drop_index(op.f("ix_operation_analyses_calculated_at"), table_name="operation_analyses")
    op.drop_table("operation_analyses")
    op.drop_index(
        op.f("ix_operation_action_executions_status"), table_name="operation_action_executions"
    )
    op.drop_index(
        op.f("ix_operation_action_executions_run_id"), table_name="operation_action_executions"
    )
    op.drop_index(
        op.f("ix_operation_action_executions_proposal_id"), table_name="operation_action_executions"
    )
    op.drop_index(
        op.f("ix_operation_action_executions_attempted_at"),
        table_name="operation_action_executions",
    )
    op.drop_table("operation_action_executions")
    op.drop_index(
        op.f("ix_operation_recommendations_run_id"), table_name="operation_recommendations"
    )
    op.drop_index(
        op.f("ix_operation_recommendations_provider_object_id"),
        table_name="operation_recommendations",
    )
    op.drop_index(
        op.f("ix_operation_recommendations_expires_at"), table_name="operation_recommendations"
    )
    op.drop_index(
        op.f("ix_operation_recommendations_created_at"), table_name="operation_recommendations"
    )
    op.drop_index(
        op.f("ix_operation_recommendations_action_type"), table_name="operation_recommendations"
    )
    op.drop_table("operation_recommendations")
    op.drop_index(op.f("ix_operation_data_snapshots_run_id"), table_name="operation_data_snapshots")
    op.drop_index(
        op.f("ix_operation_data_snapshots_collected_at"), table_name="operation_data_snapshots"
    )
    op.drop_index(
        op.f("ix_operation_data_snapshots_checksum"), table_name="operation_data_snapshots"
    )
    op.drop_index(
        op.f("ix_operation_data_snapshots_agent_id"), table_name="operation_data_snapshots"
    )
    op.drop_table("operation_data_snapshots")
    op.drop_index(op.f("ix_operation_agent_reports_run_id"), table_name="operation_agent_reports")
    op.drop_index(
        op.f("ix_operation_agent_reports_report_type"), table_name="operation_agent_reports"
    )
    op.drop_index(
        op.f("ix_operation_agent_reports_created_at"), table_name="operation_agent_reports"
    )
    op.drop_index(op.f("ix_operation_agent_reports_agent_id"), table_name="operation_agent_reports")
    op.drop_table("operation_agent_reports")
    op.drop_index(
        op.f("ix_operation_action_proposals_status"), table_name="operation_action_proposals"
    )
    op.drop_index(
        op.f("ix_operation_action_proposals_run_id"), table_name="operation_action_proposals"
    )
    op.drop_index(
        op.f("ix_operation_action_proposals_expires_at"), table_name="operation_action_proposals"
    )
    op.drop_index(
        op.f("ix_operation_action_proposals_created_at"), table_name="operation_action_proposals"
    )
    op.drop_index(
        op.f("ix_operation_action_proposals_agent_id"), table_name="operation_action_proposals"
    )
    op.drop_index(
        op.f("ix_operation_action_proposals_action_type"), table_name="operation_action_proposals"
    )
    op.drop_index("idx_operation_proposal_object", table_name="operation_action_proposals")
    op.drop_table("operation_action_proposals")
    op.drop_index(
        op.f("ix_operation_agent_schedules_next_run_at"), table_name="operation_agent_schedules"
    )
    op.drop_index(
        op.f("ix_operation_agent_schedules_job_type"), table_name="operation_agent_schedules"
    )
    op.drop_index(
        op.f("ix_operation_agent_schedules_enabled"), table_name="operation_agent_schedules"
    )
    op.drop_index(
        op.f("ix_operation_agent_schedules_agent_id"), table_name="operation_agent_schedules"
    )
    op.drop_table("operation_agent_schedules")
    op.drop_index(op.f("ix_operation_agent_runs_trigger"), table_name="operation_agent_runs")
    op.drop_index(op.f("ix_operation_agent_runs_status"), table_name="operation_agent_runs")
    op.drop_index(op.f("ix_operation_agent_runs_started_at"), table_name="operation_agent_runs")
    op.drop_index(op.f("ix_operation_agent_runs_correlation_id"), table_name="operation_agent_runs")
    op.drop_index(op.f("ix_operation_agent_runs_agent_id"), table_name="operation_agent_runs")
    op.drop_table("operation_agent_runs")
    op.drop_index(
        op.f("ix_operation_agent_configurations_agent_id"),
        table_name="operation_agent_configurations",
    )
    op.drop_index(
        op.f("ix_operation_agent_configurations_active"),
        table_name="operation_agent_configurations",
    )
    op.drop_table("operation_agent_configurations")
    op.drop_table("operation_system_controls")
    op.drop_index(op.f("ix_operation_job_locks_expires_at"), table_name="operation_job_locks")
    op.drop_table("operation_job_locks")
    op.drop_index(
        op.f("ix_operation_integration_health_status"), table_name="operation_integration_health"
    )
    op.drop_index(
        op.f("ix_operation_integration_health_checked_at"),
        table_name="operation_integration_health",
    )
    op.drop_table("operation_integration_health")
    op.drop_index(op.f("ix_operation_audit_events_run_id"), table_name="operation_audit_events")
    op.drop_index(
        op.f("ix_operation_audit_events_occurred_at"), table_name="operation_audit_events"
    )
    op.drop_index(op.f("ix_operation_audit_events_event_type"), table_name="operation_audit_events")
    op.drop_index(
        op.f("ix_operation_audit_events_correlation_id"), table_name="operation_audit_events"
    )
    op.drop_index(op.f("ix_operation_audit_events_agent_id"), table_name="operation_audit_events")
    op.drop_index(op.f("ix_operation_audit_events_actor_id"), table_name="operation_audit_events")
    op.drop_table("operation_audit_events")
    op.drop_index(op.f("ix_operation_agents_status"), table_name="operation_agents")
    op.drop_table("operation_agents")
    # ### end Alembic commands ###
